version: '3'
services:
    rabbitmq:
      image: rabbitmq:3.13-management
      ports:
        - "5672:5672"
        - "15672:15672"
      hostname: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      networks:
        - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge